/**
 *****************************************************************************
 * @title   IOToggle.c
 * @author  CooCox
 * @date    19 Jul 2012
 * @brief
 *******************************************************************************
 */
////// The above comment is automatically generated by CoIDE ///////////////////
/* Includes ------------------------------------------------------------------*/
#include "stm32f4xx.h"
#include "stm32f4xx_conf.h"
#include "5110.h"
#include "main.h"

/* Private typedef -----------------------------------------------------------*/
GPIO_InitTypeDef GPIO_InitStructure;
NVIC_InitTypeDef NVIC_InitStructure;

/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
static volatile uint32_t TimingDelay;
/* Private function prototypes -----------------------------------------------*/
void Delay(volatile uint32_t nCount);
void TimingDelay_Decrement(void);
/* Private functions ---------------------------------------------------------*/

/**
 * @brief  GPIO pin toggle program
 * @param  None
 * @retval None
 */
int main(void) {

	if (SysTick_Config(SystemCoreClock / 1000))
		while (1)
			;
	NVIC_InitStructure.NVIC_IRQChannel = SysTick_IRQn;
	NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0x0F;
	NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0x0F;
	NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&NVIC_InitStructure);

	/* GPIOA Periph clock enable */
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);

	/* Configure PA1 as output pushpull mode */
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_1;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_100MHz;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
	GPIO_Init(GPIOA, &GPIO_InitStructure);

	LCD5110_init();
	LCD5110_set_XY(0, 0);
	LCD5110_write_string("Core 407i test");
	LCD5110_write_string("              ");
	LCD5110_write_string("Nokia 5110 LCD");
	LCD5110_write_string("              ");
	LCD5110_write_string("  Build with  ");
	LCD5110_write_string("  Coocox IDE  ");

	while (1) {
		/* PA1 to be toggled */
		GPIO_SetBits(GPIOA, GPIO_Pin_1);

		/* Insert delay */
		Delay(500);

		GPIO_ResetBits(GPIOA, GPIO_Pin_1);

		/* Insert delay */
		Delay(500);
	}
}

/**
 * @brief  This function handles SysTick Handler.
 * @param  None
 * @retval None
 */
void SysTick_Handler(void) {
	TimingDelay_Decrement();
}

/**
 * @brief  Inserts a delay time.
 * @param  nTime: specifies the delay time length, in milliseconds.
 * @retval None
 */
void Delay(volatile uint32_t nTime) {
	TimingDelay = nTime;
	while (TimingDelay != 0)
		;
}

/**
 * @brief  Decrements the TimingDelay variable.
 * @param  None
 * @retval None
 */
void TimingDelay_Decrement(void) {
	if (TimingDelay > 0x00) {
		TimingDelay--;
	}
}

/******************* (C) COPYRIGHT 2011 STMicroelectronics *****END OF FILE****/
